### ISSUE TITLE
Native E-Book Reader

### ISSUE THREAD

**Issue by baxterblk** [Readarr/Readarr#2966] opened 2023-09-30 19:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This request isn't necessarily related to an issue. I'd love to see a native e-book reader within Readarr that doesn't require a 3rd party Calibre or Calibre-web which can be confusing to readers (such as my wife).

### Describe the solution you'd like

 A button within each Author and/or Book that states "Read" or similar would suffice.

### Describe alternatives you've considered

I've used both Calibre (not as a service) and Calibre-Web (in Docker), both of which are not favorites of mine. Something even more simplistic would be ideal.

### Anything else?

An extremely hypothetical mockup:

`// Reference the e-book reader library
using EBookReaderLibrary;

namespace Readarr
{
    public class EBookReaderIntegration
    {
        // Initialize the e-book reader
        private readonly IEBookReader _eBookReader;

        public EBookReaderIntegration()
        {
            // Instantiate the e-book reader with necessary parameters
            _eBookReader = new EBookReader();
        }

        // Method to open and read an e-book
        public void OpenAndReadEBook(string filePath)
        {
            // Load the e-book file
            _eBookReader.Load(filePath);

            // Open the e-book reader interface
            _eBookReader.Open();
        }
    }
}
`

**Comment by bakerboy448** [comment] 2023-10-09 14:32
Duplicate of several issues including https://github.com/Readarr/Readarr/issues/1132

No plans for this

**Closed as not planned by bakerboy448** 2023-10-09 14:32 UTC
Labels: Type: Feature Request, Type: Duplicate, Status: Won't Fix

**Comment by baxterblk** [comment] 2023-10-09 15:19
Slackers
