### ISSUE TITLE
Multiple-format releases will be parsed as the first found release with the rest ignored

### ISSUE THREAD

**Issue by trentks** [Readarr/Readarr#2053] opened 2022-12-12 01:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

It's extremely common for ebook torrents to be distributed with multiple formats present for the same book in one "pack", i.e. they will contain a .azw3, a .epub, and a .mobi. This is pretty particular to e-books, and it can be done within this medium (and often is) because the file sizes are very small, and the economy of one torrent containing multiple formats for retention/availability etc, is better than multiple torrents containing individual formats.

If you are only interested in one particular format (say .epub), and you have a release profile that reflects this desire, the parser will attribute multi-format torrents to the format that appears first in the release name (I believe, not actually tested that it's the first format, most releases I've found have their formats appear in alphabetical order, so always get parsed as .azw3).

### Expected Behavior

The parser should recognise multi-format torrents, and parse them as having multiple available formats before it goes on to filter the torrent against your release profile. Then if the release profile contains one of the multiple available formats, it should be accepted.

Or, an alternative solution: if a format isn't available within the release profile it should not be searched for by the parser.

### Steps To Reproduce

Reproduction by way of example:

1. Here's a book that has a multiple format release available (.azw3, .epub, and .mobi): ![readarr_azw3](https://user-images.githubusercontent.com/23443021/206942791-b8e041cc-6b14-45bc-9121-c1b6ea400864.png) It has parsed this release as AZW3.
2. Here's my release profile:  ![readarr_profile](https://user-images.githubusercontent.com/23443021/206942899-fe172925-ca7e-43e3-b106-e20fb99d5b1b.png) I am exclusively looking for epubs (and epub is at the top of the list).
3. Here's confirmation of what release profile is used for that books author: ![readarr_author_profile](https://user-images.githubusercontent.com/23443021/206942978-ec1f581b-745e-4b20-b9c2-ca802eefd793.png)
4. Finally, you can see that the torrent has available in its filelist an epub (as advertised in the release name): ![mam_filelist](https://user-images.githubusercontent.com/23443021/206943032-3c1f91f3-cd23-4656-9d5f-14c9b65aea35.png)

The full trace log is below, but this is the relevant excerpt:
```
2022-12-10 19:02:53.1|Trace|DownloadDecisionMaker|Processing release 1/4
2022-12-10 19:02:53.1|Debug|DownloadDecisionMaker|Processing release 'House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]' from 'MyAnonamouse-Books (Prowlarr)'
2022-12-10 19:02:53.1|Debug|Parser|Parsing string 'House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]'
2022-12-10 19:02:53.1|Trace|Parser|^(?<book>.+)\bby\b(?<author>.+?)(?:\[|\()
2022-12-10 19:02:53.1|Debug|Parser|Book Parsed. Sarah J Maas - House of Sky and Breath 
2022-12-10 19:02:53.1|Debug|QualityParser|Trying to parse quality for House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]
2022-12-10 19:02:53.1|Debug|Parser|Quality parsed: AZW3 v1
```

...

```
2022-12-10 19:02:53.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] AZW3 is not wanted in profile
```

### Environment

```markdown
- OS: Manjaro Linux
- Readarr: 0.1.1.1320 (0.0.1.1320-1 by fryfrog on the AUR)
- Docker Install: N.A.
- Using Reverse Proxy: No
- Browser: Firefox v107
- Database: 21
```

### What branch are you running?

Master

### Trace Logs?

Trace log enabled, page is already loaded and ready to perform a "manual serach" on that specific book, logs cleared, and then manual search performed:

```
2022-12-10 19:02:44.1|Trace|DiskProviderBase|Deleting file: /var/lib/readarr/logs/Readarr.debug.txt
2022-12-10 19:02:44.1|Trace|CommandQueueManager|Updating command status
2022-12-10 19:02:44.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-12-10 19:02:44.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-12-10 19:02:44.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-12-10 19:02:44.1|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-12-10 19:02:44.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-12-10 19:02:44.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-12-10 19:02:44.1|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-12-10 19:02:44.1|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-12-10 19:02:44.1|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0019495]
2022-12-10 19:02:44.1|Trace|Http|Req: 731 [GET] /api/v1/command (from 192.168.100.107 Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0)
2022-12-10 19:02:44.1|Trace|CommandQueueManager|Getting all commands
2022-12-10 19:02:44.1|Trace|Http|Res: 731 [GET] /api/v1/command: 200.OK (0 ms)
2022-12-10 19:02:44.1|Debug|Api|[GET] /api/v1/command: 200.OK (0 ms)
2022-12-10 19:02:44.1|Trace|Http|Req: 732 [GET] /api/v1/command (from 192.168.100.107 Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0)
2022-12-10 19:02:44.1|Trace|CommandQueueManager|Getting all commands
2022-12-10 19:02:44.1|Trace|Http|Res: 732 [GET] /api/v1/command: 200.OK (1 ms)
2022-12-10 19:02:44.1|Debug|Api|[GET] /api/v1/command: 200.OK (1 ms)
2022-12-10 19:02:50.6|Trace|Http|Req: 733 [GET] /api/v1/release?bookId=524 (from 192.168.100.107 Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0)
2022-12-10 19:02:50.6|Info|NzbSearchService|Searching indexers for [Sarah J. Maas - House of Sky and Breath]. 1 active indexers
2022-12-10 19:02:50.6|Debug|Torznab|Downloading Feed http://localhost:9696/5/api?t=search&cat=7000,3030,7020,7030,7010,7040&extended=1&apikey=(removed)&offset=0&limit=100&q=House%20of%20Sky%20and%20Breath%20Sarah%20J%20Maas
2022-12-10 19:02:50.6|Trace|HttpClient|Req: [GET] http://localhost:9696/5/api?t=search&cat=7000,3030,7020,7030,7010,7040&extended=1&apikey=(removed)&offset=0&limit=100&q=House%20of%20Sky%20and%20Breath%20Sarah%20J%20Maas
2022-12-10 19:02:50.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-12-10 19:02:51.6|Trace|HttpClient|Res: [GET] http://localhost:9696/5/api?t=search&cat=7000,3030,7020,7030,7010,7040&extended=1&apikey=(removed)&offset=0&limit=100&q=House%20of%20Sky%20and%20Breath%20Sarah%20J%20Maas: 200.OK (7778 bytes) (983 ms)
2022-12-10 19:02:51.6|Trace|TorznabRssParser|Parsed: House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]
2022-12-10 19:02:51.6|Trace|TorznabRssParser|Parsed: House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]
2022-12-10 19:02:51.6|Trace|TorznabRssParser|Parsed: House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]
2022-12-10 19:02:51.6|Trace|TorznabRssParser|Parsed: House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]
2022-12-10 19:02:51.6|Debug|Torznab|Downloading Feed http://localhost:9696/5/api?t=search&cat=7000,3030,7020,7030,7010,7040&extended=1&apikey=(removed)&offset=0&limit=100&q=Sarah%20J%20Maas%20House%20of%20Sky%20and%20Breath
2022-12-10 19:02:51.6|Trace|RateLimitService|Rate Limit triggered, delaying 'localhost' for 1.013 sec
2022-12-10 19:02:52.6|Trace|HttpClient|Req: [GET] http://localhost:9696/5/api?t=search&cat=7000,3030,7020,7030,7010,7040&extended=1&apikey=(removed)&offset=0&limit=100&q=Sarah%20J%20Maas%20House%20of%20Sky%20and%20Breath
2022-12-10 19:02:52.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-12-10 19:02:53.1|Trace|HttpClient|Res: [GET] http://localhost:9696/5/api?t=search&cat=7000,3030,7020,7030,7010,7040&extended=1&apikey=(removed)&offset=0&limit=100&q=Sarah%20J%20Maas%20House%20of%20Sky%20and%20Breath: 200.OK (7778 bytes) (497 ms)
2022-12-10 19:02:53.1|Trace|TorznabRssParser|Parsed: House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]
2022-12-10 19:02:53.1|Trace|TorznabRssParser|Parsed: House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]
2022-12-10 19:02:53.1|Trace|TorznabRssParser|Parsed: House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]
2022-12-10 19:02:53.1|Trace|TorznabRssParser|Parsed: House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]
2022-12-10 19:02:53.1|Debug|NzbSearchService|Total of 4 reports were found for [Sarah J. Maas - House of Sky and Breath] from 1 indexers
2022-12-10 19:02:53.1|Info|DownloadDecisionMaker|Processing 4 releases
2022-12-10 19:02:53.1|Trace|DownloadDecisionMaker|Processing release 1/4
2022-12-10 19:02:53.1|Debug|DownloadDecisionMaker|Processing release 'House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]' from 'MyAnonamouse-Books (Prowlarr)'
2022-12-10 19:02:53.1|Debug|Parser|Parsing string 'House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]'
2022-12-10 19:02:53.1|Trace|Parser|^(?<book>.+)\bby\b(?<author>.+?)(?:\[|\()
2022-12-10 19:02:53.1|Debug|Parser|Book Parsed. Sarah J Maas - House of Sky and Breath 
2022-12-10 19:02:53.1|Debug|QualityParser|Trying to parse quality for House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]
2022-12-10 19:02:53.1|Debug|Parser|Quality parsed: AZW3 v1
2022-12-10 19:02:53.1|Debug|Parser|Release Group parsed: 
2022-12-10 19:02:53.1|Trace|PreferredWordService|Calculating preferred word score for 'House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]'
2022-12-10 19:02:53.1|Trace|PreferredWordService|Calculated preferred word score for 'House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]': 0
2022-12-10 19:02:53.1|Debug|AcceptableSizeSpecification|size restriction not implemented
2022-12-10 19:02:53.1|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2022-12-10 19:02:53.1|Debug|AlreadyImportedSpecification|Performing already imported check on report
2022-12-10 19:02:53.1|Debug|AlreadyImportedSpecification|Skipping already imported check for book without files
2022-12-10 19:02:53.1|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2022-12-10 19:02:53.1|Debug|MaximumSizeSpecification|Maximum size is not set.
2022-12-10 19:02:53.1|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
2022-12-10 19:02:53.1|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. AZW3 v1
2022-12-10 19:02:53.1|Debug|QualityAllowedByProfileSpecification|Quality AZW3 v1 rejected by Author's quality profile
2022-12-10 19:02:53.1|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]
2022-12-10 19:02:53.1|Debug|ReleaseRestrictionsSpecification|[House of Sky and Breath by Sarah J Maas [ENG / azw3 epub mobi]] No restrictions apply, allowing
2022-12-10 19:02:53.1|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
2022-12-10 19:02:53.1|Debug|AuthorSpecification|Checking if author matches searched author
2022-12-10 19:02:53.1|Debug|DelaySpecification|Ignoring delay for user invoked search
2022-12-10 19:02:53.1|Debug|HistorySpecification|Skipping history check during search
2022-12-10 19:02:53.1|Debug|MonitoredBookSpecification|Skipping monitored check during search
2022-12-10 19:02:53.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] AZW3 is not wanted in profile
2022-12-10 19:02:53.1|Trace|DownloadDecisionMaker|Processing release 2/4
2022-12-10 19:02:53.1|Debug|DownloadDecisionMaker|Processing release 'House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]' from 'MyAnonamouse-Books (Prowlarr)'
2022-12-10 19:02:53.1|Debug|Parser|Parsing string 'House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]'
2022-12-10 19:02:53.1|Trace|Parser|^(?<book>.+)\bby\b(?<author>.+?)(?:\[|\()
2022-12-10 19:02:53.1|Debug|Parser|Book Parsed. Sarah J Maas - House of Sky and Breath 
2022-12-10 19:02:53.1|Debug|QualityParser|Trying to parse quality for House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]
2022-12-10 19:02:53.1|Debug|Parser|Quality parsed: M4B v1
2022-12-10 19:02:53.1|Debug|Parser|Release Group parsed: 
2022-12-10 19:02:53.1|Trace|PreferredWordService|Calculating preferred word score for 'House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]'
2022-12-10 19:02:53.1|Trace|PreferredWordService|Calculated preferred word score for 'House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]': 0
2022-12-10 19:02:53.1|Debug|AcceptableSizeSpecification|size restriction not implemented
2022-12-10 19:02:53.1|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2022-12-10 19:02:53.1|Debug|AlreadyImportedSpecification|Performing already imported check on report
2022-12-10 19:02:53.2|Debug|AlreadyImportedSpecification|Skipping already imported check for book without files
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2022-12-10 19:02:53.2|Debug|MaximumSizeSpecification|Maximum size is not set.
2022-12-10 19:02:53.2|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
2022-12-10 19:02:53.2|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. M4B v1
2022-12-10 19:02:53.2|Debug|QualityAllowedByProfileSpecification|Quality M4B v1 rejected by Author's quality profile
2022-12-10 19:02:53.2|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]
2022-12-10 19:02:53.2|Debug|ReleaseRestrictionsSpecification|[House of Sky and Breath by Sarah J Maas [ENG / m4b] [VIP]] No restrictions apply, allowing
2022-12-10 19:02:53.2|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
2022-12-10 19:02:53.2|Debug|AuthorSpecification|Checking if author matches searched author
2022-12-10 19:02:53.2|Debug|DelaySpecification|Ignoring delay for user invoked search
2022-12-10 19:02:53.2|Debug|HistorySpecification|Skipping history check during search
2022-12-10 19:02:53.2|Debug|MonitoredBookSpecification|Skipping monitored check during search
2022-12-10 19:02:53.2|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] M4B is not wanted in profile
2022-12-10 19:02:53.2|Trace|DownloadDecisionMaker|Processing release 3/4
2022-12-10 19:02:53.2|Debug|DownloadDecisionMaker|Processing release 'House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]' from 'MyAnonamouse-Books (Prowlarr)'
2022-12-10 19:02:53.2|Debug|Parser|Parsing string 'House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]'
2022-12-10 19:02:53.2|Trace|Parser|^(?<book>.+)\bby\b(?<author>.+?)(?:\[|\()
2022-12-10 19:02:53.2|Debug|Parser|Book Parsed. Sarah J Maas - House of Sky and Breath 
2022-12-10 19:02:53.2|Debug|QualityParser|Trying to parse quality for House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]
2022-12-10 19:02:53.2|Debug|Parser|Quality parsed: M4B v1
2022-12-10 19:02:53.2|Debug|Parser|Release Group parsed: 
2022-12-10 19:02:53.2|Trace|PreferredWordService|Calculating preferred word score for 'House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]'
2022-12-10 19:02:53.2|Trace|PreferredWordService|Calculated preferred word score for 'House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]': 0
2022-12-10 19:02:53.2|Debug|AcceptableSizeSpecification|size restriction not implemented
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2022-12-10 19:02:53.2|Debug|AlreadyImportedSpecification|Performing already imported check on report
2022-12-10 19:02:53.2|Debug|AlreadyImportedSpecification|Skipping already imported check for book without files
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2022-12-10 19:02:53.2|Debug|MaximumSizeSpecification|Maximum size is not set.
2022-12-10 19:02:53.2|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
2022-12-10 19:02:53.2|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. M4B v1
2022-12-10 19:02:53.2|Debug|QualityAllowedByProfileSpecification|Quality M4B v1 rejected by Author's quality profile
2022-12-10 19:02:53.2|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]
2022-12-10 19:02:53.2|Debug|ReleaseRestrictionsSpecification|[House of Sky and Breath by Sarah J Maas [ENG / m4a] [VIP]] No restrictions apply, allowing
2022-12-10 19:02:53.2|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
2022-12-10 19:02:53.2|Debug|AuthorSpecification|Checking if author matches searched author
2022-12-10 19:02:53.2|Debug|DelaySpecification|Ignoring delay for user invoked search
2022-12-10 19:02:53.2|Debug|HistorySpecification|Skipping history check during search
2022-12-10 19:02:53.2|Debug|MonitoredBookSpecification|Skipping monitored check during search
2022-12-10 19:02:53.2|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] M4B is not wanted in profile
2022-12-10 19:02:53.2|Trace|DownloadDecisionMaker|Processing release 4/4
2022-12-10 19:02:53.2|Debug|DownloadDecisionMaker|Processing release 'House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]' from 'MyAnonamouse-Books (Prowlarr)'
2022-12-10 19:02:53.2|Debug|Parser|Parsing string 'House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]'
2022-12-10 19:02:53.2|Trace|Parser|^(?<book>.+)\bby\b(?<author>.+?)(?:\[|\()
2022-12-10 19:02:53.2|Debug|Parser|Book Parsed. Sarah J Maas - House of Sky and Breath 
2022-12-10 19:02:53.2|Debug|QualityParser|Trying to parse quality for House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]
2022-12-10 19:02:53.2|Debug|Parser|Quality parsed: MP3 v1
2022-12-10 19:02:53.2|Debug|Parser|Release Group parsed: 
2022-12-10 19:02:53.2|Trace|PreferredWordService|Calculating preferred word score for 'House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]'
2022-12-10 19:02:53.2|Trace|PreferredWordService|Calculated preferred word score for 'House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]': 0
2022-12-10 19:02:53.2|Debug|AcceptableSizeSpecification|size restriction not implemented
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2022-12-10 19:02:53.2|Debug|AlreadyImportedSpecification|Performing already imported check on report
2022-12-10 19:02:53.2|Debug|AlreadyImportedSpecification|Skipping already imported check for book without files
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2022-12-10 19:02:53.2|Debug|MaximumSizeSpecification|Maximum size is not set.
2022-12-10 19:02:53.2|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
2022-12-10 19:02:53.2|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. MP3 v1
2022-12-10 19:02:53.2|Debug|QualityAllowedByProfileSpecification|Quality MP3 v1 rejected by Author's quality profile
2022-12-10 19:02:53.2|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]
2022-12-10 19:02:53.2|Debug|ReleaseRestrictionsSpecification|[House of Sky and Breath by Sarah J Maas [ENG / mp3] [VIP]] No restrictions apply, allowing
2022-12-10 19:02:53.2|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
2022-12-10 19:02:53.2|Debug|AuthorSpecification|Checking if author matches searched author
2022-12-10 19:02:53.2|Debug|DelaySpecification|Ignoring delay for user invoked search
2022-12-10 19:02:53.2|Debug|HistorySpecification|Skipping history check during search
2022-12-10 19:02:53.2|Debug|MonitoredBookSpecification|Skipping monitored check during search
2022-12-10 19:02:53.2|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] MP3 is not wanted in profile
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2022-12-10 19:02:53.2|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2022-12-10 19:02:53.2|Trace|Http|Res: 733 [GET] /api/v1/release?bookId=524: 200.OK (2559 ms)
2022-12-10 19:02:53.2|Debug|Api|[GET] /api/v1/release?bookId=524: 200.OK (2559 ms)
2022-12-10 19:02:55.0|Trace|Http|Req: 734 [GET] /logfile/Readarr.trace.txt (from 192.168.100.107 Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0)
2022-12-10 19:02:55.0|Trace|Http|Res: 734 [GET] /logfile/Readarr.trace.txt: 200.OK (2 ms)
2022-12-10 19:02:55.1|Trace|Http|Req: 735 [GET] /favicon.ico (from 192.168.100.107 Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0)
2022-12-10 19:02:55.1|Trace|Http|Res: 735 [GET] /favicon.ico: 200.OK (2 ms)
2022-12-10 19:02:59.2|Trace|Scheduler|Pending Tasks: 0
```

[AB#4431](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4431)

**Comment by DireMunchkin** [comment] 2022-12-12 13:41
I also have this issue. To me it looks like it the release parser just grabs the first format in the title by order. By example from my library `The Algebraist by Iain M Banks [ENG / epub mobi azw3]` is considered an EPUB by Readarr and `The Bitcoin Standard: The Decentralized Alternative to Central Banking by Saifedean Ammous [ENG / azw3 epub]` is considered a AZW3.

I'm currently working around it by allowing non-EPUB formats and setting upgrades allowed. The importer can mostly handle multi format releases properly so if you set EPUB as the top preferred format it'll grab just that one from a multi format release.

Downside is you will get i.e. AZW3 format only releases which you can see under Wanted > Cutoff Unmet. But it will at least correctly grab multi format releases.

**Comment by trentks** [comment] 2022-12-12 21:46
Yeah thanks for the confirmation, I suspected it was indeed the first name found in the release name that it got attributed to, but I couldn't find anything to test it against that had a non alphabetical order.

I can see how your work around works (and had considered it), but yeah that downside is a bit 'ugly'. I also don't want to run any automatic conversion on the back end. Maybe that's irrational in the e-book space, but "transcoding=bad" is too ingrained into me at this point to ever change my ways.

But yeah, this is a specific issue that's only ever going to be relevant to the e-book sphere, so I can see why it exists. There ain't no music, tv, movies, etc being released in multiple formats in the same torrent. So it may be a complicated (and novel) fix in the back-end. So I might have to consider your work-around in the interim while (if) a better man than me fixes this issue.

**Comment by bakerboy448** [comment] 2022-12-21 00:27
Duplicate of https://github.com/Readarr/Readarr/issues/1440

**Closed as not planned by bakerboy448** 2022-12-21 00:27 UTC
Labels: Type: Bug, Type: Duplicate
