### ISSUE TITLE
OPDS Server

### ISSUE THREAD

**Issue by seversonic** [Readarr/Readarr#1132] opened 2021-07-11 15:46 UTC
I hate having to manually transfer my ebooks to my ereader , or use some overbloated software to use one small feature. I self host this stuff so it would be nice to be able to use readarr to find a book, and also use some built in OPDS server to retrieve those books when added. 

**Describe the solution you'd like**
I would like an OPDS server accessible on the same url. ie) readarr.example.com/opds

**Describe alternatives you've considered**
Calibre is too big and bloated 
Ubooquity is no longer updated and the OPDS didnt work. 
Bookstack has a horrible UI and I cant get the OPDS to work

**Additional context**
As a non-developer it seems to me like a logical place to put a lightweight OPDS server would be here, but I could be very wrong. 
I dont need to read my books on an OPDS server, just distribute them. Every other software I find is both.

**Comment by bakerboy448** [comment] 2021-07-11 16:53
Duplicate of #895 

please search prior to opening issues

**Closed as completed by bakerboy448** 2021-07-11 16:53 UTC
Labels: Type: Feature Request
