### ISSUE TITLE
Mismatch on Title in Series

### ISSUE THREAD

**Issue by jun6lee** [Readarr/Readarr#3286] opened 2024-02-01 18:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![CleanShot 2024-02-01 at 23 37 38@2x](https://github.com/Readarr/Readarr/assets/6542146/0a07c2f2-ca4a-4126-9078-1617946d09d9)

### Expected Behavior

I'd expect Dexter is Delicious to map to the correct book, but it seems adamant that I'm wrong.

### Steps To Reproduce

I've checked the Tagging is correct.

### Environment

```markdown
- OS: Docker / on QNAP
- Readarr: Nightly
- Docker Install: Yes
```

### What branch are you running?

Nightly

### Trace Logs?

x

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2024-02-01 18:17
closing; invalid report

we can reopen when/if you provide the required information including environment and trace logs

**Closed as not planned by bakerboy448** 2024-02-01 18:17 UTC
Labels: Type: Bug, Status: Waiting for OP, Status: Info Needed, Status: Needs Triage, Status: Logs Needed

**Comment by mynameisbogdan** [comment] 2024-02-01 18:28
In lack of reproducing steps and logs, to me it looks like an import went wrong and not really of issue of renaming.

**Comment by jun6lee** [comment] 2024-02-06 03:53
### Environment

- OS: QTS 5.1.4 
- Readarr: Version 0.3.18.2411
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Safari
- Database: Sqlite 3.41.2 / Migration 158


### Trace Logs

[dex_trace.txt](https://github.com/Readarr/Readarr/files/14174466/dex_trace.txt)

**Comment by jun6lee** [comment] 2024-02-06 03:54
The import seems to conclude Dexter is **not** Delicious
