### ISSUE TITLE
More robust file/folder naming

### ISSUE THREAD

**Issue by sizzleweet** [Readarr/Readarr#2947] opened 2023-09-19 19:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There's no issue per-se, but I'd like to be able to have more control over my folder/file naming scheem.

### Describe the solution you'd like

For instance.

I'd like to have my folders organized as such:

{Author Last, Author First}/{if Book Series/}{if BookSeries sequence-}{BookTitle}/{partnumber:00-}{booktitle}

Currently there's no method for the "if" option.  Basically I want to be able to add that tag ONLY if it exists.  This would allow for placing book series into folders etc.

I currently do something similar to this by placing a dash into the actual tag option.  That way the dashes only appear if that tag exists and is in the naming scheme.

### Describe alternatives you've considered

Alternatives are to use the book series title and have it as a folder name along with the book title.  That way we at least get sorting based on series.

### Anything else?

Not too much.  Just hoping this makes some sense!

**Comment by bakerboy448** [comment] 2023-09-19 22:18
Duplicate of https://github.com/Readarr/Readarr/issues/1920

**Closed as not planned by bakerboy448** 2023-09-19 22:18 UTC
Labels: Type: Feature Request, Area: Organizer, Type: Duplicate
