### ISSUE TITLE
Won't Import Large Calibre Libraries

### ISSUE THREAD

**Issue by CrypticOne** [Readarr/Readarr#891] opened 2021-03-11 03:11 UTC
Reported this on discord. on v.500. Tested tonight on 520.

Calibre Server Throws a 413 error as the URL readarr tries to send is too long.

Have a large Library
Add Calibre to readarr
Get error message HTTP Error - Res: [GET] http://X.X.X.X:8081/ajax/books/books?ids=15467%2C15465%2C15464%2C15463%2C15461%2C15460%2C15459%2C15458%2C15457%2C15456%2C15453%2C15452%2C15451%2C15450%2C15449%2C15445%2C15444%2C15443%2C15442%2C15441%2C15440%2C15439%2C15438%2C15437%2C15436%2C15435%2C15434%2C15433%2C15432%2C15431%2C15430%2C15429%2C15428%2C15424%2C15425%2C15426%2C15427%2C15419%2C15420%2C15421%2C15422%2C15423%2C15414%2C15415%2C15416%2C15417%2C15418%2C15411%2C15412%2C15413%2C15410%2C15407%2C15408%2C15409%2C15404%2C15405%2C15406%2C15403%2C15402%2C15401%2C15400%2C15396%2C15397%2C15398%2C15399%2C15392%2C15393%2C15394%2C15395%2C15390%2C15391%2C15388%2C15389%2C15387%2C15386%2C15385%2C15384%2C15382%2C15383%2C15381%2C15378%2C15379%2C15380%2C15377%2C15376%2C15375%2C15373%2C15372%2C15371%2C15370%2C15369%2C15368%2C15366%2C15365%2C15364%2C15363%2C15362%2C15360%2C15359%2C15358%2C15355%2C15356%2C15357%2C15352%2C15353%2C15354%2C15350%2C15351%2C15346%2C15347%2C15348%2C15349%2C15344%2C15345%2C15342%2C15341%2C15340%2C15339%2C15338%2C15337%2C15335%2C15336%2C15334%2C15333%2C15332%2C15331%2C15330%2C15328%2C15329%2C15327%2C15326%2C15325%2C15323%2C15324%2C15322%2C15319%2C15320%2C15321%2C15315%2C15316%2C15317%2C15318%2C15314%2C15312%2C15313%2C15309%2C15310%2C15311%2C15306%2C15307%2C15308%2C15304%2C15305%2C15303%2C15302%2C15300%2C15301%2C15297%2C15298%2C15299%2C15294%2C15295%2C15296%2C15291%2C15292%2C15293%2C15289%2C15290%2C15286%2C15287%2C15288%2C15283%2C15284%2C15285%2C15281%2C15282%2C15278%2C15279%2C15280%2C15275%2C15276%2C15277%2C15272%2C15273%2C15274%2C15270%2C15271%2C15269%2C15265%2C15266%2C15268%2C15262%2C15263%2C15264%2C15261%2C15258%2C15259%2C15257%2C15256%2C15254%2C15255%2C15251%2C15252%2C15253%2C15250%2C15248%2C15249%2C15247%2C15246%2C15245%2C15244%2C15242%2C15243%2C15241%2C15240%2C15239%2C15238%2C15236%2C15237%2C15232%2C15233%2C15234%2C15235%2C15227%2C15228%2C15229%2C15230%2C15231%2C15224%2C15225%2C15226%2C15220%2C15221%2C15222%2C15223%2C15218%2C15219%2C15217%2C15214%2C15215%2C15216%2C15212%2C15213%2C15211%2C15208%2C15209%2C15210%2C15207%2C15204%2C15205%2C15206%2C15201%2C15202%2C15203%2C15199%2C15200%2C15196%2C15197%2C15198%2C15194%2C15195%2C15193%2C15192%2C15188%2C15189%2C15190%2C15191%2C15183%2C15184%2C15185%2C15186%2C15187%2C15177%2C15178%2C15179%2C15180%2C15181%2C15182%2C15174%2C15175%2C15176%2C15170%2C15171%2C15172%2C15173%2C15167%2C15168%2C15169%2C15157%2C15158%2C15156%2C15152%2C15153%2C15154%2C15150%2C15151%2C15149%2C15147%2C15148%2C15146%2C15143%2C15144%2C15145%2C15142%2C15139%2C15140%2C15138%2C15136%2C15133%2C15131%2C15132%2C15135%2C15134%2C15141%2C15129%2C15127%2C15128%2C15125%2C15126%2C15124%2C15121%2C15122%2C15123%2C15120%2C15118%2C15117%2C15115%2C15116%2C15114%2C15113%2C15112%2C15110%2C15111%2C15109%2C15108%2C15106%2C15107%2C15104%2C15105%2C15103%2C15102%2C15101%2C15099%2C15095%2C15096%2C15098%2C15094%2C15092%2C15093%2C15090%2C15089%2C15087%2C15088%2C15085%2C15086%2C15083%2C15084%2C15082%2C15091%2C15267%2C15137%2C15260%2C15081%2C15080%2C15079%2C15078%2C15077%2C15075%2C15076%2C15072%2C15073%2C15074%2C15071%2C15069%2C15070%2C15067%2C15068%2C15065%2C15066%2C15064%2C15062%2C15063%2C15061%2C15056%2C15057%2C15058%2C15059%2C15054%2C15055%2C15050%2C15051%2C15052%2C15053%2C15046%2C15047%2C15048%2C15049%2C15044%2C15045%2C15042%2C15043%2C15040%2C15041%2C15037%2C15038%2C15039%2C15035%2C15036%2C15034%2C15033%2C15032%2C15028%2C15026%2C15025%2C15023%2C15021%2C15022%2C15019%2C15020%2C15018%2C15015%2C15016%2C15017%2C15014%2C15013%2C15012%2C15010%2C15011%2C15007%2C15008%2C15009%2C15006%2C15005%2C15003%2C15004%2C15002%2C15000%2C15001%2C14999%2C14998%2C14997%2C14996%2C14994%2C14995%2C15031%2C15027%2C15024%2C15030%2C15029%2C14992%2C14991%2C14990%2C14989%2C14987%2C14988%2C14986%2C14984%2C14985%2C14983%2C14980%2C14981%2C14982%2C14978%2C14979%2C14977%2C14976%2C14975%2C14973%2C14974%2C14972%2C14971%2C14970%2C14969%2C14968%2C14967%2C14966%2C14965%2C14964%2C14963%2C14962%2C14961%2C14960%2C14959%2C14958%2C14957%2C14956%2C14955%2C14954%2C14952%2C14953%2C14951%2C14948%2C14949%2C14950%2C14944%2C14945%2C14946%2C14947%2C14943%2C14941%2C14942%2C14940%2C14938%2C14939%2C14936%2C14937%2C14935%2C14932%2C14933%2C14934%2C14929%2C14931%2C14926%2C14927%2C14928%2C14922%2C14923%2C14924%2C14925%2C14921%2C14918%2C14919%2C14920%2C14917%2C14914%2C14915%2C14916%2C14912%2C14913%2C14909%2C14910%2C14911%2C14905%2C14906%2C14907%2C14908%2C14902%2C14903%2C14904%2C14899%2C14900%2C14896%2C14897%2C14898%2C14894%2C14895%2C14891%2C14892%2C14893%2C14889%2C14890%2C14886%2C14887%2C14888%2C14883%2C14884%2C14885%2C14880%2C14881%2C14882%2C14878%2C14879%2C14875%2C14876%2C14877%2C14873%2C14874%2C14870%2C14871%2C14872%2C14868%2C14869%2C14865%2C14866%2C14867%2C14864%2C14863%2C14862%2C14861%2C14860%2C14859%2C14858%2C14857%2C14855%2C14854%2C14852%2C14851%2C14850%2C14849%2C14848%2C14847%2C14846%2C14845%2C14844%2C14843%2C14842%2C14841%2C14840%2C14839%2C14838%2C14837%2C14836%2C14835%2C14834%2C14833%2C14832%2C14831%2C14830%2C14829%2C14828%2C14827%2C14826%2C14825%2C14824%2C14823%2C14820%2C14817%2C14816%2C14814%2C14813%2C14810%2C14809%2C14808%2C14807%2C14806%2C14804%2C14801%2C14800%2C14799%2C14797%2C14796%2C14794%2C14788%2C14774%2C14762%2C14748%2C14747%2C14746%2C14930%2C14901%2C14745%2C14821%2C14822%2C14741%2C14739%2C14740%2C14737%2C14738%2C14736%2C14733%2C14734%2C14731%2C14732%2C14729%2C14730%2C14727%2C14728%2C14723%2C14724%2C14725%2C14726%2C14721%2C14722%2C14719%2C14720%2C14717%2C14718%2C14715%2C14716%2C14713%2C14714%2C14710%2C14711%2C14712%2C14708%2C14709%2C14705%2C14706%2C14707%2C14702%2C14703%2C14704%2C14701%2C14698%2C14699%2C14696%2C14697%2C14694%2C14695%2C14691%2C14692%2C14693%2C14688%2C14689%2C14690%2C14685%2C14686%2C14687%2C14682%2C14683%2C14684%2C14803%2C14681%2C14679%2C14751%2C14784%2C14780%2C14792%2C14790%2C14791%2C14786%2C14785%2C14779%2C14773%2C14771%2C14765%2C14766%2C14750%2C14761%2C14760%2C14856%2C14764%2C14763%2C14759%2C14757%2C14805%2C14756%2C14770%2C14769%2C14768%2C14795%2C14798%2C15166%2C15165%2C15163%2C15164%2C14742%2C14853%2C14755%2C14677%2C14676%2C14674%2C14669%2C14668%2C14667%2C14658%2C14656%2C14654%2C14652%2C14647%2C14644%2C14645%2C14646%2C14641%2C14638%2C14639%2C14636%2C14754%2C14753%2C14655%2C14789%2C14662%2C14672%2C14671%2C14653%2C14670%2C14633%2C14665%2C14664%2C14663%2C14640%2C14660%2C14758%2C14635%2C14793%2C14815%2C14818%2C14657%2C14632%2C14651%2C14661%2C14643%2C14666%2C14631%2C14659%2C14642%2C14678%2C14649%2C14802%2C14673%2C14812%2C14634%2C14650%2C14637%2C14629%2C14628%2C14624%2C14626%2C14621%2C14622%2C14623%2C14616%2C14617%2C14612%2C14613%2C14603%2C14604%2C14605%2C14600%2C14610%2C14783%2C14777%2C14782%2C14778%2C14776%2C14775%2C14675%2C14620%2C14625%2C14618%2C14607%2C14599%2C14611%2C14752%2C14602%2C14614%2C14619%2C14601%2C14615%2C14608%2C14648%2C14606%2C14743%2C14627%2C14609%2C14598%2C14596%2C14597%2C14593%2C14594%2C14595%2C14589%2C14590%2C14591%2C14592%2C14586%2C14587%2C14588%2C14582%2C14583%2C14584%2C14585%2C14579%2C14580%2C14581%2C14576%2C14577%2C14578%2C14573%2C14574%2C14575%2C14569%2C14570%2C14571%2C14572%2C14566%2C14567%2C14568%2C14564%2C14565%2C14563%2C14767%2C14560%2C14561%2C14562%2C14558%2C14559%2C14556%2C14557%2C14555%2C14553%2C14554%2C14551%2C14552%2C14549%2C14550%2C14547%2C14548%2C14545%2C14546%2C14544%2C14541%2C14542%2C14543%2C14538%2C14539%2C14540%2C14537%2C14535%2C14536%2C14533%2C14534%2C14532%2C14530%2C14531%2C14529%2C14528%2C14527%2C14526%2C14525%2C14522%2C14523%2C14524%2C14518%2C14519%2C14520%2C14521%2C14514%2C14515%2C14516%2C14517%2C14513%2C14507%2C14504%2C14505%2C14506%2C14502%2C14503%2C14499%2C14500%2C14501%2C14496%2C14497%2C14498%2C14494%2C14495%2C14492%2C14493%2C14491%2C14490%2C14489%2C14488%2C14487%2C14486%2C14485%2C14484%2C14483%2C14482%2C14481%2C14480%2C14479%2C14478%2C14477%2C14476%2C14475%2C14474%2C14473%2C14472%2C14471%2C14781%2C14469%2C14470%2C14468%2C14466%2C14467%2C14465%2C14463%2C14464%2C14460%2C14461%2C14462%2C14459%2C14457%2C14458%2C14455%2C14456%2C14453%2C14454%2C14452%2C14450%2C14451%2C14448%2C14449%2C14447%2C14445%2C14446%2C14444%2C14443%2C14442%2C14441%2C14439%2C14440%2C14438%2C14437%2C14436%2C14435%2C14433%2C14432%2C14431%2C14430: 413.RequestEntityTooLarge

 Readarr needs to import the books in smaller groups to keep under URL limit of 2048 characters. URL is 8000+ characters long. Each book adds 8 characters. 

Can at most safely import maybe 200 books at a time to stay under limit.

**Comment by ta264** [comment] 2021-03-12 21:02
Duplicate of #840

**Closed as completed by ta264** 2021-03-12 21:02 UTC
Labels: Type: Bug
