### ISSUE TITLE
Goodreads error causes Rescan Folders to fail and exit

### ISSUE THREAD

**Issue by garrettdowd** [Readarr/Readarr#654] opened 2020-12-15 02:22 UTC
**Describe the bug**
Folder Scan fails on Goodreads 500 error and scanning stops. Database does not seem to populate with books already scanned.

**To Reproduce**
The Goodreads search is "solomon r. guggenheim foundation". Could be unrelated.

**Platform Information (please complete the following information):**
Unraid
Version 0.1.0.338
Package Version: nightly-a8fd729-101 by hotio 
.NET Core: Yes
Docker: Yes

**Trace Logs**
```
HTTP Error - Res: [GET] https://www.goodreads.com/book/auto_complete?format=json&q=solomon%20r.%20guggenheim%20foundation: 500.InternalServerError


Search for all 'solomon r. guggenheim foundation' failed. Unable to communicate with Goodreads.: Search for all 'solomon r. guggenheim foundation' failed. Unable to communicate with Goodreads.


NzbDrone.Core.MetadataSource.Goodreads.GoodreadsException: Search for all 'solomon r. guggenheim foundation' failed. Unable to communicate with Goodreads.
   at NzbDrone.Core.MetadataSource.Goodreads.GoodreadsProxy.SearchByField(String field, String query) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\Goodreads\GoodreadsProxy.cs:line 483
   at NzbDrone.Core.MetadataSource.Goodreads.GoodreadsProxy.SearchForNewBook(String title, String author) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\Goodreads\GoodreadsProxy.cs:line 415
```

**Comment by ta264** [comment] 2021-03-18 11:03
Duplicate of #897, closing this as it has less useful logs

**Closed as completed by ta264** 2021-03-18 11:03 UTC
Labels: Type: Bug
