### ISSUE TITLE
Make book file links clickable for easy mobile device download?

### ISSUE THREAD

**Issue by lofgren007** [Readarr/Readarr#1742] opened 2022-07-17 06:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

We only download to mobile devices.  

This would typically mean opening a third party file manager with SMB support, browsing the nas file structure to media > books>author>book folder> copy book and then browse to device book folder to paste.

If books are ready and available from multiple authors, this gets pretty tedious, pretty fast.  It could be easier :)

### Describe the solution you'd like

In the readarr web interface we see the full link to each book file via browsing to:
Library > Author > Book > Files

The full path is there - if that was clickable and triggered a (hopefully) simple browser download to local /downloads (or default browser download location) that would be 90% of the work done.  Book apps *could* read from /downloads, or we could move from /downloads to /books without requiring an SMB capable app.

Even better-
The files interface in readarr already has tickable boxes (where you can trigger file deletion).  If there was an extra button there to download, users could select the books they want to download and click the download button.

Similar, but more centralised -
Same logic as the "even better" solution, but using Activity > History and a new "files" sub-section.
It would be great to see all recently downloaded books and have the ability to tick/download them rather than browse to each Author > Book > Files for each book.
Or add tick-box/download functionality under Library > books perhaps?

### Describe alternatives you've considered

Have obviously been doing this manually and tried different third party options and apps.

I understand Calibre has some download functionality - though we have a very large existing library and understand adding Calibre to a readarr library is not supported/recommended.   Calibre is also third party (to redarr) and pretty clunky.

### Anything else?

Current tickbox files/delete option:
![tickbox_delete](https://user-images.githubusercontent.com/16733115/179387215-ec71a379-f83a-4409-8e1c-8b5d2fb37baf.JPG)

[AB#3367](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3367)

**Comment by bakerboy448** [comment] 2022-07-17 16:04
Duplicate of https://github.com/Readarr/Readarr/issues/578

**Closed as not planned by bakerboy448** 2022-07-17 16:04 UTC
Labels: Type: Feature Request, Type: Duplicate
