### ISSUE TITLE
Torrent with multiple formats only imports one

### ISSUE THREAD

**Issue by SenorSmartyPants** [Readarr/Readarr#591] opened 2020-11-11 00:16 UTC
**Describe the bug**
Torrent contains single book in 3 formats. EPUB, AZW3, MOBI. Only MOBI was imported. All formats are marked as wanted/acceptable in Text quality profile.

**Expected behavior**
Have option to import all formats if all are acceptable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/991618/98749068-96ef8e00-2380-11eb-8c66-c91fbf22fca3.png)

**System info (please complete the following information):**
 - Readarr Version: nightly-375ea03-78 by hotio
 - Operating System: docker

[AB#547](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/547)

**Comment by ItsNoted** [comment] 2022-03-04 14:59
This is the same issue I am facing. I only want readarr to import audiobook files. If the torrent also contains a mobi or epub, it imports the text format over the audio versions, leaving the audio versions behind in the download folder even when my profile is set to Spoken with only audio files chosen.

**Comment by bakerboy448** [comment] 2023-01-03 22:11
closing; intended behavior

> It should only ever import a single format, the one most preferred in your quality profile
https://github.com/Readarr/Readarr/issues/1707#issuecomment-1152643207

**Closed as not planned by bakerboy448** 2023-01-03 22:11 UTC
Labels: Type: Bug, Status: Won't Fix
