### ISSUE TITLE
Error Adding Books for Monitoring

### ISSUE THREAD

**Issue by kqmaverick** [Readarr/Readarr#2156] opened 2023-01-31 02:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Receive an error when attempting to add a book

### Expected Behavior

Book is added to Readarr and is Monitored

### Steps To Reproduce

Running on either Windows or Docker, Attempt to add Matthew Perry Friends, Lovers and the Big Terrible Thing

Opening new ticket as previous was closed but issue remains after latest release despite #2151 

### Environment

```markdown
- OS: Windows & Docker
- Readarr: 0.1.1.1532
- Docker Install: 4.5.1
- Using Reverse Proxy: No
- Browser: Chrome
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

[Readarr (1).txt](https://github.com/Readarr/Readarr/files/10542235/Readarr.1.txt)

[AB#4821](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4821)

**Comment by bakerboy448** [comment] 2023-01-31 03:23
Duplicate of https://github.com/Readarr/Readarr/issues/1573

for future bug reports please see the wiki the bug report template for how to get and provide trace logs; not info logs and just the error

**Closed as not planned by bakerboy448** 2023-01-31 03:23 UTC
Labels: Type: Bug, Type: Duplicate
