### ISSUE TITLE
"Select and specify which download client is used for grabs from this indexer" feature similar to sonarr/radarr

### ISSUE THREAD

**Issue by 0x5f3** [Readarr/Readarr#1693] opened 2022-05-24 13:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I use separate clients for private and public trackers, and at the moment it isn't possible to distinguish between them using Readarr. 

### Describe the solution you'd like

The feature in sonarr/radarr nightlies which allows you to select the download client on a per-indexer basis.

### Describe alternatives you've considered

Running two instances of Readarr, but as the databases aren't synced there are often issues with post-processing and duplicate downloads.

### Anything else?

https://wiki.servarr.com/sonarr/settings#torrent-tracker-configuration > Advanced Option) Download Client - Select and specify which download client is used for grabs from this indexer

[AB#3187](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3187)

**Comment by bakerboy448** [comment] 2022-05-24 14:20
Duplicate of https://github.com/Readarr/Readarr/issues/1485

**Closed by bakerboy448** 2022-05-24 14:20 UTC
Labels: Type: Feature Request, Status: Needs Triage
