### ISSUE TITLE
Unable to select edition for manual import

### ISSUE THREAD

**Issue by bbtufty** [Readarr/Readarr#2478] opened 2023-05-11 15:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

On manual import, if I use the dropdown menu to try and select a specific edition, that is reset on exiting the menu. Looking at the logs, it seems it simply defaults to using the best match whatever edition is selected here

### Expected Behavior

The edition should be updated to reflect my choice

### Steps To Reproduce

1. Select manual import
2. Select -> Select edition
3. Attempt to change to any edition
4. This change is not saved

### Environment

```markdown
- OS: Ubuntu
- Readarr: 0.1.4.1596
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome (but also Safari)
- Database: Sqlite 3.40.1
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/bbtufty/c0a1cf7489b75c40765bbe102c5f0dd6#file-readarr_trace-log

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2023-05-11 15:33
what do you mean reset? where is it being reset compared to? Manual Import does not display edition anywhere and pretty sure if you're saying select edition then trying to select edition again, it goes to what it detected as default and this would be a non-issue.

Are you referring to the Book => Edit => Edition not matching the edition set in manual import? if so that is expected and not a bug.  Book Edition is the edition you want and has no relation to the edition on disk.

**Comment by bbtufty** [comment] 2023-05-11 15:47
as in when you manual import, if you 'select edition', when you then import it does not respect this change. This is generally pretty harmless but I'm finding it's appending things like "(Unabridged)" to the name, or actually changing the name of the book itself if this edition matching isn't how I want it to be. I just tried selection edition as a paperback, then importing an audiobook and it's added an 'Unabridged' to the end so clearly the edition selection is not kept

**Comment by YodaDaCoda** [comment] 2024-02-23 06:28
This appears to be a duplicate of #2472 ?

**Comment by bakerboy448** [comment] 2024-02-23 13:17
Duplicate of #2472

**Closed as not planned by bakerboy448** 2024-02-23 13:17 UTC
Labels: Type: Bug, Type: Duplicate
