### ISSUE TITLE
DiskScanService.cs Scan() function doesn't create empty author folders if check box is flagged in UI.

### ISSUE THREAD

**Issue by dny238** [Readarr/Readarr#2142] opened 2023-01-20 22:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Checkbox in Media settings called "Create Empty Author Folder" does not create an empty folder when checked.

### Expected Behavior

When the checkbox in the UI's Media Settings called "Create Empty Author Folder" is ticked and saved, and a new authors is added, an empty folder should be created. 

(Created a branch called fix-CreateEmptyAuthorFolders with two commits to fix this issue and pushed them 1/20/2023.
Commit 1 improves the Scan() function to utilize the authorIDs variable to get the authors folders
Commit 1 uses the author folders variable to create a new folder if it's missing)

### Steps To Reproduce

1) Check the box in settings
2) Add a new author
3) Observe that no empty folder is created for that author

### Environment

```markdown
- OS: Windows
- Readarr: current
- Docker Install:
- Using Reverse Proxy:
- Browser:
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

the trace log does not display any errors identifying this issue

[AB#4770](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4770)

**Comment by bakerboy448** [comment] 2023-01-20 23:02
Duplicate of https://github.com/Readarr/Readarr/issues/435

for future reference `current` is not a valid version.  The version can be found in system => status

**Closed as not planned by bakerboy448** 2023-01-20 23:02 UTC
Labels: Type: Bug, Type: Duplicate
