### ISSUE TITLE
[FEAT]: Would like a monitoring option for "just this book".

### ISSUE THREAD

**Issue by mumblingsages** [Readarr/Readarr#1206] opened 2021-08-19 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

If I search for a book by doing the following: Library -> Add Book -> <book name>, and add it to the library I get all books from that author being monitored. I rarely read ALL books from a given author, especially when it is the first time I'm reading their material. 

### Describe the solution you'd like

I would like a new monitoring option to be added to Readarr, that adds only the book I've searched for. Maybe call it "This Book Only" or something that comes across like that to the end user. 

### Describe alternatives you've considered

I did try to use a metadata option of 'none' while monitoring the Author. However, this results in my library no longer showing all the rest of the material published by that author. 

### Anything else?

This was discussed between me (mumblingsages) and ta264 in Discord on  08/19/2021 at 0949 CST. 

[AB#1470](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1470)

**Comment by ItsME6969** [comment] 2021-09-26 23:47
+1.
I only want 5 books from 5 very popular authors and as a result, I have hundreds of unwanted books in my library. Having to process all those extra unwanted books is also more taxing on the system with regards to the scheduled tasks. Just RL Stine adds 488 books to the Library. It would be nice if I only had 5 books in my Library. @ta264 
![Screenshot 2021-09-26 163933 - Copy](https://user-images.githubusercontent.com/89707006/134828254-9954e820-98b5-4ca6-8ac4-09e55e4b34c7.jpg)

**Comment by bakerboy448** [comment] 2021-09-26 23:48
> +1.
> I only want 5 books from 5 very popular authors and as a result, I have hundreds of unwanted books in my library. Having to process all those extra unwanted books is also more taxing on the system with regards to the scheduled tasks. Just RL Stine adds 488 books to the Library. It would be nice if I only had 5 books in my Library. 

Sounds like the existing Metadata option of None is exactly what you want

**Comment by ItsME6969** [comment] 2021-09-27 00:51
> > +1.
> > I only want 5 books from 5 very popular authors and as a result, I have hundreds of unwanted books in my library. Having to process all those extra unwanted books is also more taxing on the system with regards to the scheduled tasks. Just RL Stine adds 488 books to the Library. It would be nice if I only had 5 books in my Library.
> 
> Sounds like the existing Metadata option of None is exactly what you want

Oh great, I didn't realize that's how it worked thanks.

**Comment by ItsME6969** [comment] 2021-09-27 01:14
Sorry, one last question @bakerboy448 when that single book is deleted the author still remains and I have to delete the author separately, is this intended behavior or a bug, or maybe something I'm doing wrong?

**Comment by bakerboy448** [comment] 2021-10-28 01:33
> Sorry, one last question @bakerboy448 when that single book is deleted the author still remains and I have to delete the author separately, is this intended behavior or a bug, or maybe something I'm doing wrong?

Intended I believe.

think of authors as tv series and books as episodes to put it simply

sorry for the delayed response - didn't see it

**Comment by bakerboy448** [comment] 2021-12-04 04:13
@ta264  does https://github.com/Readarr/Readarr/commit/c51ae664aa6e6f5330be67e68476af76c55352f5 and https://github.com/Readarr/Readarr/commit/33e5351addae0cf1df44aa201417bb9b5e817fbd

Close this?

**Comment by ta264** [comment] 2022-01-20 10:42
It does

**Closed as completed by ta264** 2022-01-20 10:42 UTC
Labels: Type: Feature Request
