### ISSUE TITLE
Current issues with metadata cause readarr to delete authors!

### ISSUE THREAD

**Issue by phit42** [Readarr/Readarr#3069] opened 2023-11-15 21:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Readarr is running a refresh author in the background, hits an unexpected issue in getting info and suddenly deletes the author and all related files! It even sends out a nice notification about it "author removed and all files were deleted"
No interaction with the frontend at the time of the deletion, or any time after the restart of the container before the issue.

### Expected Behavior

Should definitely not delete anything out of the blue.

### Steps To Reproduce

Unknown, but happened multiple times, I think I lost at least 4 authors because of the issue.

### Environment

```markdown
Version 0.3.10.2287
Package Version 0.3.10.2287-ls74 by linuxserver.io
.NET Core Yes (6.0.21)
Docker Yes
DB Migration 158
Database Sqlite 3.41.2
AppData directory /config
Startup directory /app/readarr/bin
Mode Console
Uptime 1d 21:00:20
```

### What branch are you running?

Master

### Trace Logs?

`2023-11-15 20:54:13.9|Info|RefreshAuthorService|Updating Info for C.J. Archer
2023-11-15 20:54:14.0|Warn|BookInfoProxy|Unexpected error getting author info

[v0.3.10.2287] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Unexpected error fetching author data
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthorUncached(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 633
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.<>c__DisplayClass30_0.<PollAuthor>b__0() in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 588
   at LazyCache.AppCacheExtensions.<>c__DisplayClass7_0`1.<GetOrAdd>b__0(ICacheEntry _)
   at LazyCache.CachingService.<>c__DisplayClass22_1`1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at LazyCache.CachingService.GetValueFromLazy[T](Object item, Boolean& valueHasChangedType)
   at LazyCache.CachingService.GetOrAdd[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
   at LazyCache.AppCacheExtensions.GetOrAdd[T](IAppCache cache, String key, Func`1 addItemFactory, MemoryCacheEntryOptions policy)
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthor(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 587
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetAuthorInfo(String foreignAuthorId, Boolean useCache) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 99

2023-11-15 20:54:14.0|Error|RefreshAuthorService|Could not find author with id 4615377
2023-11-15 20:54:14.0|Info|RefreshAuthorService|Updating Info for C.J. Archer
2023-11-15 20:54:14.1|Warn|RefreshAuthorService|Author [4615377][C.J. Archer] not found in metadata and is being deleted
2023-11-15 20:54:17.0|Info|MetadataService|Author folder does not exist, skipping metadata creation`

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2023-11-15 22:04
Duplicate of numerous existing issues. The data  is / shouldn't actually being deleted from the database from what's been seen

**Closed as completed** 2023-11-15 22:05 UTC
Labels: Type: Support
