### ISSUE TITLE
Book Counting Improvements - Feature Request

### ISSUE THREAD

**Issue by Dude77777** [Readarr/Readarr#1929] opened 2022-11-07 09:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When checking the library view it would be great to get a much more accurate view of how many complete books rather than files one has in his / her collection. I'd argue that 95% of all books are present in mp3 with multiple files rather than aac etc, therefore the solution needs to accurately take multi file books into account.

### Describe the solution you'd like

Ideally Readarr displays how many complete books (rather than files) are present, so as ratio complete books / selected books. This would make the dynamic colouring correct - currently a lot is red because I have 11/4 etc. 

### Describe alternatives you've considered

I believe this feature is present in other arrs

### Anything else?

I believe this feature is present in other arrs

[AB#4037](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4037)

**Comment by PearsonFlyer** [comment] 2022-11-07 12:54
Duplicate of #1509 
https://github.com/Readarr/Readarr/issues/1509

**Closed as completed by PearsonFlyer** 2022-11-07 12:54 UTC
Labels: Type: Feature Request, Type: Duplicate
