### ISSUE TITLE
Ability to download both Spoken and eBook formats for author/book

### ISSUE THREAD

**Issue by bcorbet** [Readarr/Readarr#2413] opened 2023-04-28 20:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not a problem, but I like spoken audio books and my daughter likes written ebooks, but we like to read similar books.

### Describe the solution you'd like

Solution would be to have a check box on the Author/book to select ebook and/or audio.  Now it seems like the media profile is only on the author and you are not able to create a profile that downloads both formats.

### Describe alternatives you've considered

I have tried to accomplish this with the media profiles but it does not seem to work.  It will randomly download either ebook or audio, but not both.

### Anything else?

Nothing else, but thank you for this project

**Comment by bakerboy448** [comment] 2023-04-28 20:12
Duplicate of https://github.com/Readarr/Readarr/issues/1329

**Closed as not planned by bakerboy448** 2023-04-28 20:12 UTC
Labels: Type: Feature Request, Type: Duplicate
