### ISSUE TITLE
Add a series of books

### ISSUE THREAD

**Issue by BulldozerPete** [Readarr/Readarr#3589] opened 2024-07-25 16:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have to manually search for each book in this series: https://www.goodreads.com/series/129764-osprey-new-vanguard

### Describe the solution you'd like

Add a series, like adding an author or book

### Describe alternatives you've considered

Haven't found one.

### Anything else?

Link to a series: https://www.goodreads.com/series/129764-osprey-new-vanguard

**Comment by bakerboy448** [comment] 2024-07-25 17:30
Duplicate of https://github.com/Readarr/Readarr/issues/1236

>  I have searched the existing open and closed issues

please don't blindly check the box.
https://github.com/Readarr/Readarr/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+-label%3Asonarr-pull+series

**Closed as not planned by bakerboy448** 2024-07-25 17:30 UTC
Labels: Type: Feature Request, Type: Duplicate
