### ISSUE TITLE
Config option for ImportDecisionMaker threshold or disable auto imports by author

### ISSUE THREAD

**Issue by meguthe** [Readarr/Readarr#3436] opened 2024-04-16 10:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've got an issue where some books are being automatically imported incorrectly and being overwritten. The issue comes from the author naming the books as a series and not using subtitles. 

This issue is similar to #588, but in the opposite direction. Instead of not automatically importing a book because it barely doesn't meet the threshold, it automatically imports the wrong book because the threshold is too lenient.  

### Describe the solution you'd like

I'd like an option to disable the automatic imports for the author, altogether, or change the threshold to be lower, so it doesn't automatically import the wrong book.

### Describe alternatives you've considered

A dangerous fix that I've found is to manually edit the database. I wouldn't recommend this.

### Anything else?

An example of this happening is if the books are titled as shown below.
Series Title
Series  Title 2
Series Title 3

**Comment by bakerboy448** [comment] 2024-04-16 10:07
Duplicate of https://github.com/Readarr/Readarr/issues/588

no plans to make the threshold user configurable.  Evidence supporting changing the threshold can be discussed and shared in discord so far no user has ever provided any

> change the threshold to be lower, so it doesn't automatically import the wrong book.

a lower threshold would not prevent imports and would allow more imports.

**Closed as not planned by bakerboy448** 2024-04-16 10:07 UTC
Labels: Type: Feature Request, Type: Duplicate, Status: Won't Fix

**Comment by meguthe** [comment] 2024-04-16 10:08
I wanted to use a higher threshold.

**Comment by meguthe** [comment] 2024-04-16 10:09
90% or higher.

**Comment by bakerboy448** [comment] 2024-04-16 10:15
Does not change the duplicate issue / answer

**Comment by meguthe** [comment] 2024-04-16 10:18
> Does not change the duplicate issue / answer

Could a feature to disable auto imports at least be added? I don't like that readarr is deleting books because it thinks all 3 books in a book series are book 1. The only way I've been able to fix it is by stopping readarr, editing the database, and hardlinking the files myself.

**Comment by bakerboy448** [comment] 2024-04-16 10:21
Please use [Discord](http://readarr.com/discord) for support/questions.

completed download handling can already be disabled

**Comment by meguthe** [comment] 2024-04-16 10:31
That's not really disabling based on author, but it will help for now. Thanks.
