### ISSUE TITLE
We are currently experiencing issues with our metadata provider, this will prevent user searches and author refreshes from working. We are working to solve the issue.

### ISSUE THREAD

**Issue by HeisenbergK** [Readarr/Readarr#3110] opened 2023-12-06 05:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

e.g. I search for "Rowling" in authors and I get no results.

### Expected Behavior

I should get a list of authors, including J. K. Rowling.

### Steps To Reproduce

Version: 0.3.10.2287
.NET Core: Yes (6.0.21)
Docker: Yes
DB Migration: 158
Database: Sqlite 3.41.2
AppData directory: /config
Startup directory: /app/readarr/bin
Mode: Console

### Environment

```markdown
- OS: Unknown
- Readarr: Readarr 0.3.10.2287
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome & Chromium (not related)
- Database: Sqlite 3.41.2
```

### What branch are you running?

Nightly

### Trace Logs?

[readarr.0.txt](https://github.com/Readarr/Readarr/files/13576655/readarr.0.txt)
[readarr.txt](https://github.com/Readarr/Readarr/files/13576657/readarr.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by danleitch** [comment] 2023-12-06 08:52
☝🏼 + 1

**Comment by bakerboy448** [comment] 2023-12-06 10:52
Duplicate of https://github.com/Readarr/Readarr/issues/3106
Duplicate of #2970 

Ref https://github.com/Readarr/Readarr/issues/2970#issuecomment-1822031496

**Closed as not planned by bakerboy448** 2023-12-06 10:52 UTC
Labels: Type: Duplicate, Type: Support

**Comment by bakerboy448** [comment] 2023-12-06 11:08
https://wiki.servarr.com/readarr/system#we-are-currently-experiencing-issues-with-our-metadata-provider-this-will-prevent-user-searches-and-author-refreshes-from-working-we-are-working-to-solve-the-issue

**Comment by bakerboy448** [comment] 2024-09-18 14:47
For users coming here from Google. Please see the pinned messages in discord, the pinned GitHub Issues, or the wiki page for current metadata server issues/status

https://wiki.servarr.com/readarr/metadata-issues
