### ISSUE TITLE
Add Author to the Interactive Search window

### ISSUE THREAD

**Issue by bthuree** [Readarr/Readarr#3348] opened 2024-03-05 04:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If perform an Manual search for a wanted book, and get say 50+ books in the result.
The title of your search window only displays the book title, and not the author.
Might be 20 different books with the same title but different authors to choose between

### Describe the solution you'd like

Would be great if the title window instead of displaying

_Interactive Search - Hold the Line_

displays something like this

**Interactive Search - Chris Hechtl: Hold the Line**

### Describe alternatives you've considered

n/a

### Anything else?

n/a

**Comment by bthuree** [comment] 2024-03-05 04:24
Forgot the reason :) 
The window will cover everything if the result have a lot of titles in it.

**Comment by mynameisbogdan** [comment] 2024-03-06 05:37
Duplicate of #3343

**Closed as not planned by mynameisbogdan** 2024-03-06 05:37 UTC
Labels: Type: Feature Request, Status: Needs Triage
