### ISSUE TITLE
“Ignore deleted books” flag is impossible to set

### ISSUE THREAD

**Issue by mybuntu-git2** [Readarr/Readarr#1694] opened 2022-05-24 16:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Under Settings>media management>file management
Flag for “ignore deleted books”
Setting the flag and saving the flag as “on”: the flag reverts to “off”.

### Expected Behavior

Flag saved when set, like other flags behave.

### Steps To Reproduce

As indicated going to the flag and saving with the save changes button.

### Environment

```markdown
- OS: Ubuntu 20.04 
- Readarr: 0.1.1.1320
- Docker Install: no
- Using Reverse Proxy: no
- Browser: safari (not from same machine)
```

### What branch are you running?

Develop

### Trace Logs?

2022-05-24 17:57:32.0|Trace|Http|Req: 157 [GET] /api/v1/config/naming/examples?renameBooks=true&replaceIllegalCharacters=true&standardBookFormat=%7BBook%20Title%7D%2F%7BAuthor%20Name%7D%20-%20%7BBook%20Title%7D%7B%20(PartNumber)%7D&authorFolderFormat=%7BAuthor%20Name%7D&includeAuthorName=false&includeBookTitle=false&includeQuality=false&replaceSpaces=false&id=1 (from 10.8.0.7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15)
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'autounmonitorpreviouslydownloadedtracks' defaultValue:'False'
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'watchlibraryforchanges' defaultValue:'True'
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'rescanafterrefresh' defaultValue:'Always'
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'allowfingerprinting' defaultValue:'NewFiles'
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'chmodfolder' defaultValue:'755'
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'importextrafiles' defaultValue:'False'
2022-05-24 17:57:32.0|Trace|ConfigService|Using default config value for 'extrafileextensions' defaultValue:'srt'
2022-05-24 17:57:32.0|Trace|Http|Res: 158 [GET] /api/v1/config/mediamanagement: 200.OK (43 ms)
2022-05-24 17:57:32.0|Debug|Api|[GET] /api/v1/config/mediamanagement: 200.OK (43 ms)
2022-05-24 17:57:32.0|Trace|Http|Res: 156 [GET] /api/v1/config/naming: 200.OK (45 ms)
2022-05-24 17:57:32.0|Debug|Api|[GET] /api/v1/config/naming: 200.OK (45 ms)
2022-05-24 17:57:32.0|Trace|Http|Req: 159 [GET] /api/v1/remotepathmapping (from 10.8.0.7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15)
2022-05-24 17:57:32.1|Trace|Http|Res: 157 [GET] /api/v1/config/naming/examples?renameBooks=true&replaceIllegalCharacters=true&standardBookFormat=%7BBook%20Title%7D%2F%7BAuthor%20Name%7D%20-%20%7BBook%20Title%7D%7B%20(PartNumber)%7D&authorFolderFormat=%7BAuthor%20Name%7D&includeAuthorName=false&includeBookTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (60 ms)
2022-05-24 17:57:32.1|Debug|Api|[GET] /api/v1/config/naming/examples?renameBooks=true&replaceIllegalCharacters=true&standardBookFormat=%7BBook%20Title%7D%2F%7BAuthor%20Name%7D%20-%20%7BBook%20Title%7D%7B%20(PartNumber)%7D&authorFolderFormat=%7BAuthor%20Name%7D&includeAuthorName=false&includeBookTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (60 ms)
2022-05-24 17:57:32.1|Trace|Http|Res: 159 [GET] /api/v1/remotepathmapping: 200.OK (15 ms)
2022-05-24 17:57:32.1|Debug|Api|[GET] /api/v1/remotepathmapping: 200.OK (15 ms)
2022-05-24 17:57:32.1|Trace|Http|Res: 155 [GET] /api/v1/rootFolder: 200.OK (83 ms)
2022-05-24 17:57:32.1|Debug|Api|[GET] /api/v1/rootFolder: 200.OK (83 ms)
2022-05-24 17:57:41.1|Trace|Http|Req: 160 [PUT] /api/v1/config/mediamanagement (from 10.8.0.7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15)
2022-05-24 17:57:41.1|Trace|Http|Req: 161 [PUT] /api/v1/config/naming (from 10.8.0.7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15)
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'autounmonitorpreviouslydownloadedtracks' defaultValue:'False'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'15'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'removefaileddownloads' defaultValue:'True'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
2022-05-24 17:57:41.1|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2022-05-24 17:57:41.2|Trace|Http|Res: 161 [PUT] /api/v1/config/naming: 202.Accepted (23 ms)
2022-05-24 17:57:41.2|Debug|Api|[PUT] /api/v1/config/naming: 202.Accepted (23 ms)
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'60'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'importextrafiles' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'extrafileextensions' defaultValue:'srt'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'watchlibraryforchanges' defaultValue:'True'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'rescanafterrefresh' defaultValue:'Always'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'allowfingerprinting' defaultValue:'NewFiles'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'chmodfolder' defaultValue:'755'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'writeaudiotags' defaultValue:'No'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'writebooktags' defaultValue:'NewFiles'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'embedmetadata' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-05-24 17:57:41.2|Trace|ConfigService|Writing Setting to database. Key:'autounmonitorpreviouslydownloadedbooks' Value:'True'
2022-05-24 17:57:41.2|Trace|EventAggregator|Publishing ConfigSavedEvent
2022-05-24 17:57:41.2|Trace|EventAggregator|ConfigSavedEvent -> RootFolderWatchingService
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'watchlibraryforchanges' defaultValue:'True'
2022-05-24 17:57:41.2|Trace|EventAggregator|ConfigSavedEvent <- RootFolderWatchingService
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'autounmonitorpreviouslydownloadedtracks' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2022-05-24 17:57:41.2|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2022-05-24 17:57:41.2|Trace|EventAggregator|ConfigSavedEvent ~> TaskManager
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'15'
2022-05-24 17:57:41.2|Trace|ServerSideNotificationService|Getting server side health notifications
2022-05-24 17:57:41.2|Trace|HttpClient|Req: [GET] https://readarr.servarr.com/v1/notification?version=0.1.1.1320&os=linux&arch=Arm64&runtime=netcore&branch=develop
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'watchlibraryforchanges' defaultValue:'True'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'rescanafterrefresh' defaultValue:'Always'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'allowfingerprinting' defaultValue:'NewFiles'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'chmodfolder' defaultValue:'755'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'importextrafiles' defaultValue:'False'
2022-05-24 17:57:41.2|Trace|ConfigService|Using default config value for 'extrafileextensions' defaultValue:'srt'
2022-05-24 17:57:41.2|Trace|Http|Res: 160 [PUT] /api/v1/config/mediamanagement: 202.Accepted (106 ms)
2022-05-24 17:57:41.2|Debug|Api|[PUT] /api/v1/config/mediamanagement: 202.Accepted (106 ms)
2022-05-24 17:57:41.2|Trace|EventAggregator|ConfigSavedEvent <~ TaskManager
2022-05-24 17:57:41.4|Trace|HttpClient|Res: [GET] https://readarr.servarr.com/v1/notification?version=0.1.1.1320&os=linux&arch=Arm64&runtime=netcore&branch=develop: 200.OK (2 bytes) (213 ms)
2022-05-24 17:57:41.4|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-05-24 17:57:41.4|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-05-24 17:57:41.4|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-05-24 17:57:41.4|Trace|Http|Req: 162 [GET] /api/v1/health (from 10.8.0.7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15)
2022-05-24 17:57:41.5|Trace|Http|Res: 162 [GET] /api/v1/health: 200.OK (3 ms)
2022-05-24 17:57:41.5|Debug|Api|[GET] /api/v1/health: 200.OK (3 ms)
2022-05-24 17:57:45.9|Trace|Http|Req: 163 [GET] /api/v1/config/host (from 10.8.0.7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15)
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-05-24 17:57:45.9|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-05-24 17:57:45.9|Trace|Http|Res: 163 [GET] /api/v1/config/host: 200.OK (22 ms)
2022-05-24 17:57:45.9|Debug|Api|[GET] /api/v1/config/host: 200.OK (22 ms)
2022-05-24 17:57:52.0|Trace|Http|Req: 164 [PUT] /api/v1/config/host (from 10.8.0.7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15)
2022-05-24 17:57:52.1|Trace|EventAggregator|Publishing ConfigFileSavedEvent
2022-05-24 17:57:52.1|Trace|EventAggregator|ConfigFileSavedEvent ~> ReconfigureLogging

[AB#3188](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3188)

**Comment by bakerboy448** [comment] 2022-05-24 16:03
Duplicate of https://github.com/Readarr/Readarr/issues/1505

**Comment by bakerboy448** [comment] 2022-05-24 16:03
> Is there an existing issue for this?
>> [X] I have searched the existing issues

Please search next time

**Closed as not planned by bakerboy448** 2022-05-24 16:03 UTC
Labels: Type: Bug, Type: Duplicate
