### ISSUE TITLE
Mass Editor doesn't seem to work

### ISSUE THREAD

**Issue by kahn10** [Readarr/Readarr#17] opened 2020-05-09 01:32 UTC
**Describe the bug**
I've selected a large number of books and tried to change the root folder as well as add a tag. I've tried both selecting all the files (including ones which are present in the destination folder) and only ones which need to be moved. I don't see anything pending in the tasks list related to this, though I am currently doing a large import. At some point I was able to get files to move successfully, though I'm not sure what is different between the two situations. I have tried both selecting "move files" and "don't move files". Adding tags similarly doesn't seem to work. Selecting only one author also doesn't work.

I have tried stopping and restarting my server several times to no effect. The program is able to read and write to both folders.

**To Reproduce**
Add books to list.
Go to Mass Editor
Select books to move
select destination folder at the bottom

**Expected behavior**
The files should update their location

**Logs**
There is nothing in the logs which indicate attempt or failure to change the folder

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.60 - docker (also occurred in 0.1.0.58)
 - Operating System: MacOS 10.13.6 (High Sierra)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Unknown
Issuing "mono --version" in the docker image returns "mono: not found"

[AB#1056](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1056)

**Comment by bakerboy448** [comment] 2021-04-12 01:09
Is this still occurring on recent builds?

**Comment by kahn10** [comment] 2021-04-12 01:18
This problem seems to still be an issue. I just tested on on the most recent nightly and it does not change the root folder.

**Comment by bakerboy448** [comment] 2021-07-03 16:48
Cannot reproduce this on `0.1.0.792`  Ubuntu 20.04

Mass Editor -> Select an Author -> Change Root Folder -> Yes Move Files.

```
2021-07-03 11:46:12.0|Trace|AuthorService|Changing path for Nicholas Sparks to /data/media/media/books-tmp/Nicholas Sparks
2021-07-03 11:46:12.0|Trace|CommandExecutor|BulkMoveAuthorCommand -> MoveAuthorService
2021-07-03 11:46:12.0|Trace|CommandQueueManager|Marking command as started: BulkMoveAuthor
2021-07-03 11:46:12.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
2021-07-03 11:46:12.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2021-07-03 11:46:12.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2021-07-03 11:46:12.0|Info|MoveAuthorService|Moving 1 author to '/data/media/media/books-tmp/'
2021-07-03 11:46:12.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
2021-07-03 11:46:12.0|Debug|AuthorService|1 authors updated
2021-07-03 11:46:12.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2021-07-03 11:46:12.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2021-07-03 11:46:12.0|Trace|Http|Res: 954 [PUT] /readarr/api/v1/author/editor: 202.Accepted (180 ms)
2021-07-03 11:46:12.0|Info|MoveAuthorService|Moving Nicholas Sparks from '/data/media/media/books/Nicholas Sparks' to '/data/media/media/books-tmp/Nicholas Sparks' (1/1)
2021-07-03 11:46:12.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
2021-07-03 11:46:12.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2021-07-03 11:46:12.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2021-07-03 11:46:12.0|Trace|RootFolderWatchingService|reporting start of change to /data/media/media/books/Nicholas Sparks
2021-07-03 11:46:12.0|Trace|RootFolderWatchingService|reporting start of change to /data/media/media/books-tmp/Nicholas Sparks
2021-07-03 11:46:12.0|Debug|DiskTransferService|Move Directory [/data/media/media/books/Nicholas Sparks] > [/data/media/media/books-tmp/Nicholas Sparks]
2021-07-03 11:46:12.1|Debug|DiskTransferService|Rename Directory [/data/media/media/books/Nicholas Sparks] > [/data/media/media/books-tmp/Nicholas Sparks]
2021-07-03 11:46:12.1|Info|MoveAuthorService|Nicholas Sparks moved successfully to /data/media/media/books-tmp/Nicholas Sparks
```

Closing

Can reopen if needed.... if/when trace logs and file system `ls-lha` are provided that demonstrate this issue exists

**Closed as completed by bakerboy448** 2021-07-03 16:48 UTC
Labels: Status: Waiting for OP
